# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a741a941294dad33ff3dbdfd9f4f0ebaafb753ad2d761056c76a70f85d824d98f31195b165d3d31e84ee4ec3b686772522e27a1dfaaa888592e6b9cbea3bc461

test:
  secret_key_base: 407f8285c7ea0aaf934f45d2855a08e0907ad678d0c117aaca41e064f0d83158aec01acc0b05c7f2d88a857778179a4c58b6492af2ad0b4389081a01dbec749c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
